### ISSUE TITLE
API docs in md or hosted?

### ISSUE THREAD

**Issue by evemorgen** [CanSatKit/CanSatKitLibrary#19]
I'm a bit concerned about lack of API documentation - since it is cool lib and I would love to see it more accessible for newbies. 
IMO it would be nice to have even small `md` file with public api description or maybe more pro way - have it automagically generated from code and pushed to [readthedocs](https://readthedocs.org) or something similar.

-- edit
Actualy - [there is a script for that already](https://github.com/circuitar/ArduinoDocs) 😄

**Comment by begreeen** [comment]
Sure, we're actively thinking about it. 👍 
The reason why documentation in library wasn't our main focus is that newbies actually have no clue where the libraries (I mean, sources) are located (after installation in Arduino, especially via Library Manager). The main goal before competition kick off was to provide the teams with some examples that would cover most of the use cases (especially for beginners). 
Actually, public API is rather concise so I believe that adding docs will not take ages. 😄 Readthedocs sounds nice (however rather for more advanced users, but I believe that beginners are covered by presentations from workshop and examples).

**Comment by ggajoch** [comment]
@evemorgen I've tested library you've mentioned. It is too simple for our case, especially considering that this library consists of couple of separate parts. However on that basis I've started building the documentation - https://github.com/CanSatKit/CanSatKitLibrary/tree/docs/docs.
Simplest method would be to host pure doxygen outputs, however http://readthedocs.org/ looks awesome!

**Comment by begreeen** [comment]
Resolved in https://github.com/CanSatKit/CanSatKitLibrary/pull/21
