### ISSUE TITLE
Board reset

### ISSUE THREAD

**Issue by kubapat** [CanSatKit/CanSatKitLibrary#24]
Hello!
I'm not sure I'm writing this question in appropriate place, but how can I reset manually CanSat board based on Arduino M0. There's a nReset PIN, but I dont't what should I do with it.

Thanks in advance

**Comment by begreeen** [comment]
Hi,
Check the [user manual](https://github.com/CanSatKit/Documentation/blob/master/CanSatKit_User_Manual_PL.pdf) (page 14): 

![image](https://user-images.githubusercontent.com/6267528/56415880-61132200-628f-11e9-93d3-8258e52fb56f.png)

I hope it'll work for you!

**Comment by kubapat** [comment]
Thanks. That helped!
